// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRSystem.Models;

public partial class Attendance
{
    public int AttendanceId { get; set; }

    public string EmployeeCode { get; set; }

    public int DeviceId { get; set; }

    public DateTime CheckTime { get; set; }

    public string CheckType { get; set; }

    public int? VerifyMode { get; set; }

    public virtual FingerDevice Device { get; set; }

    public virtual Employee EmployeeCodeNavigation { get; set; }
}