// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRSystem.Models;

public partial class Branch
{
    public int BranchId { get; set; }

    public string BranchCode { get; set; }

    public string BranchName { get; set; }

    public string City { get; set; }

    public bool? IsActive { get; set; }

    public string VpnIp { get; set; }
    
    public string ZkAccessDbPath { get; set; }
    public string ZkUsername { get; set; }
    public string ZkPassword { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<FingerDevice> FingerDevices { get; set; } = new List<FingerDevice>();

    public virtual ICollection<DvrDevice> DvrDevices { get; set; } = new List<DvrDevice>();
}