// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRSystem.Models;

public partial class Employee
{
    public string No { get; set; }

    public string SearchName { get; set; }

    public string EnglishName { get; set; }

    public int? BranchId { get; set; }

    public string DivisionCode { get; set; }

    public string DepartmentCode { get; set; }

    public string SectionCode { get; set; }

    public string PositionCode { get; set; }

    public string LocationCode { get; set; }

    public string EmployeeStatus { get; set; }

    public DateOnly? EmploymentDate { get; set; }

    public DateOnly? ActiveDate { get; set; }

    public string ContractType { get; set; }

    public DateOnly? ContractStartDate { get; set; }

    public DateOnly? ContractEndDate { get; set; }

    public string CurrentWorkShift { get; set; }

    public string JobGrade { get; set; }

    public string NationalId { get; set; }

    public DateOnly? BirthDate { get; set; }

    public string Gender { get; set; }

    public string Religion { get; set; }

    public string MobilePhoneNo { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string ShiftUser { get; set; }
    public string start_shift { get; set; }
    public string end_shift { get; set; }
    public string Hours { get; set; }

    public string MilitaryCode { get; set; }

    public bool? Disabled { get; set; }

    public int? Age { get; set; }

    public bool? HasSocialInsurance { get; set; }

    public string SocialInsuranceNo { get; set; }

    public DateOnly? SocialInsuranceDate { get; set; }

    public string EducationLevel { get; set; }

    public string EducationDegree { get; set; }

    public int? GraduationYear { get; set; }

    public string Comment { get; set; }

    public string Photo { get; set; }
    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();
    public virtual Branch Branch { get; set; }

    // New HR Modules Navigation
    public virtual ICollection<EmployeeDocument> Documents { get; set; } = new List<EmployeeDocument>();
    public virtual ICollection<LeaveRequest> LeaveRequests { get; set; } = new List<LeaveRequest>();
    public virtual ICollection<LeaveBalance> LeaveBalances { get; set; } = new List<LeaveBalance>();
    public virtual SalaryStructure SalaryStructure { get; set; }
    public virtual ICollection<Payslip> Payslips { get; set; } = new List<Payslip>();
    public virtual ICollection<EmployeeLoan> Loans { get; set; } = new List<EmployeeLoan>();
}