// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRSystem.Models;

public partial class FingerDevice
{
    public int DeviceId { get; set; }

    public string DeviceName { get; set; }

    public string Ipaddress { get; set; }

    public int? Port { get; set; }

    public string SerialNumber { get; set; }

    public int? BranchId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? LastSyncTime { get; set; }
    
    public string AccessDbPath { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual Branch Branch { get; set; }
}