// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace HRSystem.Models;

public partial class HRContext : IdentityDbContext<ApplicationUser>
{
    public HRContext(DbContextOptions<HRContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Attendance> Attendances { get; set; }
    public virtual DbSet<Branch> Branches { get; set; }
    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<FingerDevice> FingerDevices { get; set; }
    public virtual DbSet<UserSessionLog> UserSessionLogs { get; set; }
    public virtual DbSet<DvrDevice> DvrDevices { get; set; }

    // New HR Modules
    public virtual DbSet<LeaveType> LeaveTypes { get; set; }
    public virtual DbSet<LeaveBalance> LeaveBalances { get; set; }
    public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }
    public virtual DbSet<EmployeeDocument> EmployeeDocuments { get; set; }
    public virtual DbSet<SalaryStructure> SalaryStructures { get; set; }
    public virtual DbSet<Payslip> Payslips { get; set; }
    public virtual DbSet<EmployeeLoan> EmployeeLoans { get; set; }
    public virtual DbSet<LoanDeduction> LoanDeductions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.ToTable("Attendance");

            // تحويل الفهارس إلى Covering Indexes لسرعة خرافية في البحث بالتاريخ
            entity.HasIndex(e => e.CheckTime).HasDatabaseName("IX_Attendance_CheckTime")
                .IncludeProperties(e => new { e.EmployeeCode, e.DeviceId, e.CheckType });
            
            entity.HasIndex(e => e.EmployeeCode).HasDatabaseName("IX_Attendance_EmployeeCode");
            entity.HasIndex(e => e.DeviceId).HasDatabaseName("IX_Attendance_DeviceId");

            entity.Property(e => e.CheckTime).HasColumnType("datetime");
            entity.Property(e => e.CheckType).HasMaxLength(10);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Device).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attendance_FingerDevice");

            entity.HasOne(d => d.EmployeeCodeNavigation).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.EmployeeCode)
                .HasConstraintName("FK_Attendance_Employees");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasIndex(e => e.BranchCode, "UQ__Branches__1C61B888585B193A").IsUnique();

            entity.Property(e => e.BranchCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.BranchName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.No);

            entity.Property(e => e.No)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("No.");
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.ContractType).HasMaxLength(50);
            entity.Property(e => e.CurrentWorkShift).HasMaxLength(50);
            entity.Property(e => e.DepartmentCode).HasMaxLength(50);
            entity.Property(e => e.Disabled).HasDefaultValue(false);
            entity.Property(e => e.DivisionCode).HasMaxLength(50);
            entity.Property(e => e.EducationDegree).HasMaxLength(100);
            entity.Property(e => e.EducationLevel).HasMaxLength(50);
            entity.Property(e => e.EmployeeStatus).HasMaxLength(20);
            entity.Property(e => e.EnglishName).HasMaxLength(250);
            entity.Property(e => e.Gender).HasMaxLength(10);
            entity.Property(e => e.HasSocialInsurance).HasDefaultValue(false);
            entity.Property(e => e.JobGrade).HasMaxLength(50);
            entity.Property(e => e.LocationCode).HasMaxLength(50);
            entity.Property(e => e.MilitaryCode).HasMaxLength(20);
            entity.Property(e => e.MobilePhoneNo).HasMaxLength(20);
            entity.Property(e => e.NationalId)
                .HasMaxLength(14)
                .HasColumnName("NationalID");
            entity.Property(e => e.PositionCode).HasMaxLength(50);
            entity.Property(e => e.Religion).HasMaxLength(20);
            entity.Property(e => e.SearchName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.SectionCode).HasMaxLength(50);
            entity.Property(e => e.SocialInsuranceNo).HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.Employees)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_Employees_Branches");
        });

        modelBuilder.Entity<FingerDevice>(entity =>
        {
            entity.HasKey(e => e.DeviceId);

            entity.ToTable("FingerDevice");

            entity.Property(e => e.DeviceName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Ipaddress)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("IPAddress");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Port).HasDefaultValue(4370);
            entity.Property(e => e.SerialNumber).HasMaxLength(50);
            entity.Property(e => e.LastSyncTime).HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.FingerDevices)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_FingerDevice_Branches");
        });

        modelBuilder.Entity<DvrDevice>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.ToTable("DvrDevices");

            entity.Property(e => e.DvrName).IsRequired().HasMaxLength(100);
            entity.Property(e => e.LocalIp).IsRequired().HasMaxLength(50);
            entity.Property(e => e.VpnPort).HasDefaultValue(3777);
            entity.Property(e => e.Username).IsRequired().HasMaxLength(100);
            entity.Property(e => e.Password).IsRequired().HasMaxLength(100);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.LastSyncTime).HasColumnType("datetime");

            entity.HasOne(d => d.Branch).WithMany(p => p.DvrDevices)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_DvrDevices_Branches");
        });

        OnModelCreatingPartial(modelBuilder);

        // ─── LeaveType ────────────────────────────────────────
        modelBuilder.Entity<LeaveType>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.Name).IsRequired().HasMaxLength(50);
            e.Property(x => x.NameAr).HasMaxLength(50);
            e.Property(x => x.ColorClass).HasMaxLength(30).HasDefaultValue("primary");
        });

        // ─── LeaveBalance ──────────────────────────────────────
        modelBuilder.Entity<LeaveBalance>(e =>
        {
            e.HasKey(x => x.Id);
            e.HasIndex(x => new { x.EmployeeNo, x.LeaveTypeId, x.Year }).IsUnique();
            e.Property(x => x.EmployeeNo).IsRequired().HasMaxLength(20).IsUnicode(false);
            e.Property(x => x.TotalDays).HasPrecision(8, 2);
            e.Property(x => x.UsedDays).HasPrecision(8, 2);
            e.Property(x => x.PendingDays).HasPrecision(8, 2);
            e.Ignore(x => x.RemainingDays);
            e.HasOne(x => x.Employee).WithMany(x => x.LeaveBalances)
                .HasForeignKey(x => x.EmployeeNo)
                .HasConstraintName("FK_LeaveBalance_Employee");
            e.HasOne(x => x.LeaveType).WithMany(x => x.Balances)
                .HasForeignKey(x => x.LeaveTypeId);
        });

        // ─── LeaveRequest ──────────────────────────────────────
        modelBuilder.Entity<LeaveRequest>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.EmployeeNo).IsRequired().HasMaxLength(20).IsUnicode(false);
            e.Property(x => x.ManagerNo).HasMaxLength(20).IsUnicode(false);
            e.Property(x => x.Reason).HasMaxLength(500);
            e.Property(x => x.ManagerNotes).HasMaxLength(500);
            e.Property(x => x.HRNotes).HasMaxLength(500);
            e.Property(x => x.StartDate).HasColumnType("date");
            e.Property(x => x.EndDate).HasColumnType("date");
            e.Property(x => x.CreatedAt).HasColumnType("datetime").HasDefaultValueSql("getdate()");
            e.HasOne(x => x.Employee).WithMany(x => x.LeaveRequests)
                .HasForeignKey(x => x.EmployeeNo)
                .HasConstraintName("FK_LeaveRequest_Employee")
                .OnDelete(DeleteBehavior.Restrict);
            e.HasOne(x => x.LeaveType).WithMany(x => x.Requests)
                .HasForeignKey(x => x.LeaveTypeId);
        });

        // ─── EmployeeDocument ─────────────────────────────────
        modelBuilder.Entity<EmployeeDocument>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.EmployeeNo).IsRequired().HasMaxLength(20).IsUnicode(false);
            e.Property(x => x.DocumentType).IsRequired().HasMaxLength(50);
            e.Property(x => x.FileName).IsRequired().HasMaxLength(255);
            e.Property(x => x.FilePath).IsRequired().HasMaxLength(500);
            e.Property(x => x.Notes).HasMaxLength(500);
            e.Ignore(x => x.IsExpired);
            e.Ignore(x => x.DaysUntilExpiry);
            e.HasOne(x => x.Employee).WithMany(x => x.Documents)
                .HasForeignKey(x => x.EmployeeNo)
                .HasConstraintName("FK_EmployeeDocument_Employee");
        });

        // ─── SalaryStructure ──────────────────────────────────
        modelBuilder.Entity<SalaryStructure>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.EmployeeNo).IsRequired().HasMaxLength(20).IsUnicode(false);
            e.Property(x => x.BaseSalary).HasPrecision(18, 2);
            e.Property(x => x.HousingAllowance).HasPrecision(18, 2);
            e.Property(x => x.TransportAllowance).HasPrecision(18, 2);
            e.Property(x => x.MedicalAllowance).HasPrecision(18, 2);
            e.Property(x => x.OtherAllowances).HasPrecision(18, 2);
            e.Property(x => x.TaxRate).HasPrecision(5, 4);
            e.Property(x => x.SocialInsuranceRate).HasPrecision(5, 4);
            e.Property(x => x.Notes).HasMaxLength(500);
            e.Ignore(x => x.GrossSalary);
            e.HasOne(x => x.Employee).WithOne(x => x.SalaryStructure)
                .HasForeignKey<SalaryStructure>(x => x.EmployeeNo)
                .HasConstraintName("FK_SalaryStructure_Employee");
        });

        // ─── Payslip ──────────────────────────────────────────
        modelBuilder.Entity<Payslip>(e =>
        {
            e.HasKey(x => x.Id);
            e.HasIndex(x => new { x.EmployeeNo, x.Month, x.Year }).IsUnique();
            e.Property(x => x.EmployeeNo).IsRequired().HasMaxLength(20).IsUnicode(false);
            e.Property(x => x.BaseSalary).HasPrecision(18, 2);
            e.Property(x => x.GrossSalary).HasPrecision(18, 2);
            e.Property(x => x.HousingAllowance).HasPrecision(18, 2);
            e.Property(x => x.TransportAllowance).HasPrecision(18, 2);
            e.Property(x => x.MedicalAllowance).HasPrecision(18, 2);
            e.Property(x => x.OtherAllowances).HasPrecision(18, 2);
            e.Property(x => x.TaxAmount).HasPrecision(18, 2);
            e.Property(x => x.SocialInsuranceAmount).HasPrecision(18, 2);
            e.Property(x => x.LoanDeductionAmount).HasPrecision(18, 2);
            e.Property(x => x.OtherDeductions).HasPrecision(18, 2);
            e.Property(x => x.TotalDeductions).HasPrecision(18, 2);
            e.Property(x => x.NetSalary).HasPrecision(18, 2);
            e.Property(x => x.PdfPath).HasMaxLength(500);
            e.Property(x => x.GeneratedAt).HasColumnType("datetime").HasDefaultValueSql("getdate()");
            e.HasOne(x => x.Employee).WithMany(x => x.Payslips)
                .HasForeignKey(x => x.EmployeeNo)
                .HasConstraintName("FK_Payslip_Employee");
        });

        // ─── EmployeeLoan ─────────────────────────────────────
        modelBuilder.Entity<EmployeeLoan>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.EmployeeNo).IsRequired().HasMaxLength(20).IsUnicode(false);
            e.Property(x => x.TotalAmount).HasPrecision(18, 2);
            e.Property(x => x.MonthlyInstallment).HasPrecision(18, 2);
            e.Property(x => x.RemainingAmount).HasPrecision(18, 2);
            e.Property(x => x.Notes).HasMaxLength(500);
            e.Ignore(x => x.PaidInstallments);
            e.HasOne(x => x.Employee).WithMany(x => x.Loans)
                .HasForeignKey(x => x.EmployeeNo)
                .HasConstraintName("FK_EmployeeLoan_Employee");
        });

        // ─── LoanDeduction ────────────────────────────────────
        modelBuilder.Entity<LoanDeduction>(e =>
        {
            e.HasKey(x => x.Id);
            e.Property(x => x.Amount).HasPrecision(18, 2);
            e.Property(x => x.DeductionDate).HasColumnType("datetime");
            e.HasOne(x => x.Loan).WithMany(x => x.Deductions)
                .HasForeignKey(x => x.LoanId);
            e.HasOne(x => x.Payslip).WithMany(x => x.LoanDeductions)
                .HasForeignKey(x => x.PayslipId);
        });
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}